added version checking

diff --git a/miner-manager b/miner-manager
--- a/miner-manager
+++ b/miner-manager
@@ -17,6 +17,10 @@ MINER_ARCHIVE_FOLDER="$MINER_BRANCH"
 
 # Get miner files and setup temporary opt/
 f.PREPMINER(){
+if [ "$(echo $VER | sed 's/\.//g')" -ne 133 ] ; then
+  echo "Unable to install"
+  exit 14
+fi
   echo "Getting latest release of miner"
   curl -s https://api.github.com/repos/$GIT_USER_REPO/releases \
   | grep -i "browser_download_url.*$MINER_BRANCH.*t.*z" \
@@ -99,7 +103,6 @@ f.PREPETHOS(){
 
 # Gather stock ethOS files in temporary opt/ and install stock packages
 f.REVERT(){
-VER=$(grep -oE "[0-9]+\.[0-9]+\.[0-9]+" /opt/ethos/etc/version)
 if [ "$(echo $VER | sed 's/\.//g')" -lt 132 ] ; then
   echo "Unable to revert"
   exit 14
@@ -130,7 +133,7 @@ fi
 f.INSTALL(){
   echo "Stopping the miner"
   /opt/ethos/bin/disallow
-ps uax | egrep "avermore|ccminer|cgminer-skein|claymore|dstm-zcash|ethminer|ewbf-equihash|ewbf-zcash|lolminer|nevermore|optiminer-zcash|progpowminer|sgminer-gm|teamredminer|xmr-stak|xtl-stak|$MINER_BRANCH" | grep -Ev '(curl|update-miner|miner-manager|grep)' | awk '{print $2}' | sudo xargs kill -9
+  ps uax | egrep "avermore|ccminer|cgminer-skein|claymore|dstm-zcash|ethminer|ewbf-equihash|ewbf-zcash|lolminer|nevermore|optiminer-zcash|progpowminer|sgminer-gm|teamredminer|xmr-stak|xtl-stak|$MINER_BRANCH" | grep -Ev '(curl|update-miner|miner-manager|develop|grep)' | awk '{print $2}' | sudo xargs kill -9
   
   echo "Installing miner"
   sudo rsync -av "$TMP_DIR/opt/" /opt
@@ -152,14 +155,14 @@ f.HELP (){
 Usage $CMD [ Miner ] ( install | update | revert )
 
 Miners Available:
-$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master)')"
+$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master|develop)')"
 }
 
 # TODO add logging
 if [ "$#" -ne "2" ] ; then
   f.HELP "Wrong number of arguments"
   exit 1
-elif [[ "$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master)')" == *" $MINER_BRANCH "* ]] ; then
+elif [[ "$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master|develop)')" == *" $MINER_BRANCH "* ]] ; then
   f.HELP "Invalid miner selected, Please choose from the list below"
   exit 2
 fi
@@ -170,6 +173,7 @@ source <(curl -s https://raw.githubusercontent.com/cynixx3/third-party-miner-ins
 echo "Move to a temporary work space"
 mkdir "$TMP_DIR"
 cd "$TMP_DIR" || exit 10
+VER=$(grep -oE "[0-9]+\.[0-9]+\.[0-9]+" /opt/ethos/etc/version)
 
 case "$2" in
   install)
