better exit messages

diff --git a/miner-manager b/miner-manager
--- a/miner-manager
+++ b/miner-manager
@@ -17,10 +17,6 @@ MINER_ARCHIVE_FOLDER="$MINER_BRANCH"
 
 # Get miner files and setup temporary opt/
 f.PREPMINER(){
-if [ "$(echo $VER | sed 's/\.//g')" -ne 133 ] ; then
-  echo "Unable to install"
-  exit 14
-fi
   echo "Getting latest release of miner"
   DOWNLOAD_URL=$(curl -s https://api.github.com/repos/$GIT_USER_REPO/releases \
   | grep -i "browser_download_url.*$MINER_BRANCH.*t.*z" \
@@ -38,14 +34,14 @@ fi
   if [ -f $MINER_BRANCH.$COMPRESSION ] ; then rm -rf /tmp/newminer/$MINER_BRANCH.$COMPRESSION ; fi
   
   if ! wget -q $DOWNLOAD_URL -O "$MINER_BRANCH.$COMPRESSION" ; then
-    echo "Download failed"
+    echo "Download failed. Please check your firewall or git access and try again."
     exit 10
   fi
 
   if [ $RELEASE_SHASUM ] ; then
     echo "Comparing download with checksum"
     if ! echo "$RELEASE_SHASUM $MINER_BRANCH.$COMPRESSION" | sha256sum -c ; then
-      echo "checksum of miner files failed, please try again or update miner.settings in repo"
+      echo "Check of miner files failed, please check your access to git then try again or update miner.settings in repo"
       exit 11
     fi
   fi
@@ -58,7 +54,7 @@ fi
     echo "WARNING: tarbomb detected. Opening in subdirectory, $MINER_ARCHIVE_FOLDER."
   fi
   if ! tar "$CT" -xf "$MINER_BRANCH.$COMPRESSION" "$SUBDIR" ; then
-    echo "Unable to extract files package. please try again."
+    echo "Unable to extract files package. Please check your access to git then try again."
     exit 12
   fi
   
@@ -90,6 +86,10 @@ f.CHECKDPKG(){
 
 # Get Replacement ethos files that enable miner operation and install miner specific dependencies
 f.PREPETHOS(){
+if [ "$(echo $VER | sed 's/\.//g')" -ne 133 ] ; then
+  echo "Unable to install due to current ethOS version, try \"update\" instead to install just the miner or update ethOS."
+  exit 14
+fi
   echo "Download and unpack files needed by ethOS"
 #todo add ethos version checking
   git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b "$MINER_BRANCH"
@@ -135,7 +135,7 @@ f.PREPETHOS(){
 # Gather stock ethOS files in temporary opt/ and install stock packages
 f.REVERT(){
 if [ "$(echo $VER | sed 's/\.//g')" -lt 132 ] ; then
-  echo "Unable to revert"
+  echo "Unable to revert, stock files are not ready for your miner version. Please try `sudo ethos-update reupdate`"
   exit 14
 fi
   git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-$VER
@@ -185,7 +185,7 @@ f.INSTALL(){
 
 f.CLEANUP(){
   rm -rf "$TMP_DIR"
-  echo "temporary files removed"
+  echo "temporary files removed, all done."
 }
 
 f.HELP (){
@@ -198,7 +198,7 @@ $(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-e
 
 # TODO add logging
 if [ "$#" -ne "2" ] ; then
-  f.HELP "Wrong number of arguments"
+  f.HELP "Wrong number of arguments, must be 2 arguments miner and action, please refer to https://github.com/cynixx3/third-party-miner-installer-for-ethos"
   exit 1
 elif [[ "$(curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/branches | grep name | cut -d '"' -f 4 | grep -Ev '(1.3|master|develop)')" == *" $MINER_BRANCH "* ]] ; then
   f.HELP "Invalid miner selected, Please choose from the list below"
