removed need for archive folder setting

diff --git a/miner-manager b/miner-manager
--- a/miner-manager
+++ b/miner-manager
@@ -11,7 +11,6 @@ ACTION="$2"
 # Default miner.settings
 TMP_DIR="/tmp/newminer"
 GIT_USER_REPO="cynixx3/third-party-miner-installer-for-ethos"
-MINER_ARCHIVE_FOLDER="$MINER_BRANCH"
 #RELEASE_SHASUM="sha256sum of archive"
 #DEPENDS="URL URL"
 
@@ -23,7 +22,7 @@ f.PREPMINER(){
   | cut -d '"' -f 4 \
   | grep -vE '(osx|txt)' \
   | head -1 )
-  COMPRESSION=$(echo $DOWNLOAD_URL | grep -oP 't[argxb.]{1,4}z2?$')
+  COMPRESSION=$(echo "$DOWNLOAD_URL" | grep -oP 't[argxb.]{1,4}z2?$')
   case $COMPRESSION in
     tar.gz|tgz) CT="-z" ;;
     tar.xz) CT="-J" ;;
@@ -31,14 +30,14 @@ f.PREPMINER(){
     *) CT="" ;;
   esac
 
-  if [ -f $MINER_BRANCH.$COMPRESSION ] ; then rm -rf /tmp/newminer/$MINER_BRANCH.$COMPRESSION ; fi
+  if [ -f "$MINER_BRANCH.$COMPRESSION" ] ; then rm -rf "/tmp/newminer/$MINER_BRANCH.$COMPRESSION" ; fi
   
-  if ! wget -q $DOWNLOAD_URL -O "$MINER_BRANCH.$COMPRESSION" ; then
+  if ! wget -q "$DOWNLOAD_URL" -O "$MINER_BRANCH.$COMPRESSION" ; then
     echo "Download failed. Please check your firewall or git access and try again."
     exit 10
   fi
 
-  if [ $RELEASE_SHASUM ] ; then
+  if [ "$RELEASE_SHASUM" ] ; then
     echo "Comparing download with checksum"
     if ! echo "$RELEASE_SHASUM $MINER_BRANCH.$COMPRESSION" | sha256sum -c ; then
       echo "Check of miner files failed, please check your access to git then try again or update miner.settings in repo"
@@ -49,9 +48,11 @@ f.PREPMINER(){
   echo "Unpacking miner"
   SUBDIR=""
   if tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | grep -qv "^$(tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | sort | head -n1 )" ; then
-    SUBDIR="--directory=$MINER_ARCHIVE_FOLDER" 
-    mkdir "$MINER_ARCHIVE_FOLDER"
-    echo "WARNING: tarbomb detected. Opening in subdirectory, $MINER_ARCHIVE_FOLDER."
+    SUBDIR="--directory=$MINER_BRANCH" 
+    mkdir "$MINER_BRANCH"
+    echo "WARNING: tarbomb detected. Opening in subdirectory, $MINER_BRANCH."
+  else
+    MINER_ARCHIVE_FOLDER=$(tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | head -n1 | cut -d / -f 1) || echo "failed to find archive folder"
   fi
   if ! tar "$CT" -xf "$MINER_BRANCH.$COMPRESSION" "$SUBDIR" ; then
     echo "Unable to extract files package. Please check your access to git then try again."
