improved tarbomb detection

diff --git a/miner-manager b/miner-manager
--- a/miner-manager
+++ b/miner-manager
@@ -49,12 +49,12 @@ f.PREPMINER(){
 
   echo "Unpacking miner"
   SUBDIR=""
-  if tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | grep -qv "^$(tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | sort | head -n1 )" ; then
+  if tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | grep -qv "^$(tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | grep -oP '^.*\/' | head -n1 )" ; then
     SUBDIR="--directory=$MINER_BRANCH" 
     mkdir "$MINER_BRANCH"
     echo "WARNING: tarbomb detected. Opening in subdirectory, $MINER_BRANCH."
   else
-	  MINER_ARCHIVE_FOLDER=$(tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | grep -oP '^.*\/' | grep -vE '(kernel|plugin)' | sort -u | tail -n1) || echo "failed to find archive folder"
+  MINER_ARCHIVE_FOLDER=$(tar "$CT" -tf "$MINER_BRANCH.$COMPRESSION" | grep -oP '^.*\/' | grep -vE '(kernel|plugin)' | sort -u | tail -n1) || echo "failed to find archive folder"
   fi
   if ! tar "$CT" -xf "$MINER_BRANCH.$COMPRESSION" "$SUBDIR" ; then
     echo "Unable to extract files package. Please check your access to git then try again."
