playing with versioning

diff --git a/miner-manager b/miner-manager
--- a/miner-manager
+++ b/miner-manager
@@ -99,8 +99,12 @@ f.PREPETHOS(){
 
 # Gather stock ethOS files in temporary opt/ and install stock packages
 f.REVERT(){
-#todo add ethos version checking
-  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-1.3.3
+VER=$(grep -oE "[0-9]+\.[0-9]+\.[0-9]+" /opt/ethos/etc/version)
+if [ "$(echo $VER | sed 's/\.//g')" -lt 132 ] ; then
+  echo "Unable to revert"
+  exit 14
+fi
+  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-$VER
   mkdir -p "$TMP_DIR/opt/ethos"
   rsync -a --delete "$TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/" "$TMP_DIR/opt/ethos"
   chmod 775 "$TMP_DIR"/opt/ethos/bin/* "$TMP_DIR"/opt/ethos/sbin/* 
@@ -114,7 +118,6 @@ f.REVERT(){
   sudo chown -R root.root "$TMP_DIR"/opt/ethos/
   sudo chown -R ethos.ethos "$TMP_DIR"/opt/ethos/etc/screenrc.* "$TMP_DIR"/opt/ethos/bin/minestop
 # Reinstall stock dependencies
-#todo add ethos version checking
   mkdir "$TMP_DIR/depends"
   wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-4.8/gcc-4.8-base_4.8.4-2ubuntu1~14.04.4_amd64.deb -P depends
   wget https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/14981774/+files/gcc-8-base_8.1.0-5ubuntu1~14.04_amd64.deb -P depends
