more fixes

diff --git a/phoenix-installer b/phoenix-installer
--- a/phoenix-installer
+++ b/phoenix-installer
@@ -1,32 +1,32 @@
 #!/bin/bash
 
 # This is not intended to be a working script, it is mearly an example of what developers can do
+TMP_DIR=/tmp/newminer
+echo "Move to a temporary work space"
+mkdir $TMP_DIR
+cd $TMP_DIR
 
 f.prepminer(){
-  echo "Getting Miner"
-  echo "Move to a temporary work space"
-  mkdir /tmp/newminer
-  cd /tmp/newminer
-  
   echo "Getting latest release of miner"
   curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/releases/latest \
   | grep "browser_download_url.*tar\.gz" \
   | cut -d '"' -f 4 \
   | head -1 \
   | wget -qi - -O PhoenixMiner.tar.gz
+
   echo "Comparing download with checksum"
   echo "354307c366d32b37793022aced287f6a76dc1037e98ab18d1af400bc532ba0d2 PhoenixMiner.tar.gz" | sha256sum -c 
-  if [ "$?" -ne "0" ]; then echo "checksum of downloaded files failed, please try again";exit 0; fi
+  if [ "$?" -ne "0" ]; then echo "checksum of downloaded files failed, please try again";exit 1; fi
   
   echo "Unpacking miner"
-  tar xzf PhoenixMiner.tar.gz
+  tar xzf $TMP_DIR/PhoenixMiner.tar.gz
   if [ "$?" != "0" ]; then
     echo "Unable to extract files package. please try again."
-    exit 0
+    exit 2
   fi
   
-  mkdir -p opt/miners
-  rsync -a --delete PhoenixMiner_4.0b_Linux/ opt/miners/phoenixminer
+  mkdir -p $TMP_DIR/opt/miners
+  rsync -a --delete $TMP_DIR/PhoenixMiner_4.0b_Linux/ $TMP_DIR/opt/miners/phoenixminer
   
   echo "Temporary miner files ready"
 }
@@ -51,27 +51,31 @@ f.prepethos(){
   echo "Download and unpack files needed by ethOS"
   git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b phoenixminer
   
-  mkdir opt/ethos
-  rsync -a --delete third-party-miner-installer-for-ethos/opt/ethos/ opt/ethos
-  
+  mkdir -p $TMP_DIR/opt/ethos
+  rsync -a --delete $TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/ $TMP_DIR/opt/ethos
+  chmod ug+x $TMP_DIR/opt/ethos/*
+
 #  echo "Check for dependencies"
 #  if [ $(dpkg-query -W -f='${Status}' gcc-5 2>/dev/null | grep -c "ok installed") -eq 0 ] ; then
 #    echo "Installing dependencies"
-#    mkdir depends
+#    mkdir $TMP_DIR/depends
 #    wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/gcc-5-base_5.4.0-6ubuntu1~16.04.10_amd64.deb -P depends
 #    wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb -P depends
 #    f.checkdpkg
 #    sudo dpkg --configure -a
 #    f.checkdpkg
-#    sudo dpkg -i depends/*.deb
+#    sudo dpkg -i $TMP_DIR/depends/*.deb
 #  fi
   
   echo "ethOS files ready"
 }
 
 f.revert(){
-  cd /tmp/newminer
   git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-1.3.3
+  mkdir -p $TMP_DIR/opt/ethos
+  rsync -a --delete $TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/ $TMP_DIR/opt/ethos
+  chmod ug+x $TMP_DIR/opt/ethos/lib/* $TMP_DIR/opt/ethos/bin/* $TMP_DIR/opt/ethos/sbin/*
+  chmod u+x $TMP_DIR/opt/ethos/etc/*
 }
 
 f.install(){
@@ -80,7 +84,7 @@ f.install(){
   /opt/ethos/bin/minestop
   
   echo "Installing miner"
-  sudo rsync -av opt/ /opt
+  sudo rsync -av $TMP_DIR/opt/ /opt
   sudo chown -R ethos.ethos /opt/miners/
   
   echo "Restarting services and miner"
@@ -91,7 +95,7 @@ f.install(){
 }
 
 f.cleanup(){
-  rm -rf /tmp/newminer
+  rm -rf $TMP_DIR
 }
 
 case "$1" in
