working example

diff --git a/third-party-miner-installer-for-ethos b/third-party-miner-installer-for-ethos
--- a/third-party-miner-installer-for-ethos
+++ b/third-party-miner-installer-for-ethos
@@ -1,35 +1,35 @@
 #!/bin/bash
 
-# This is not meant to be a working script, it is mearly an example of what developers can do
+# This is not intended to be a working script, it is mearly an example of what developers can do
+TMP_DIR=/tmp/newminer
+echo "Move to a temporary work space"
+mkdir $TMP_DIR
+cd $TMP_DIR
 
 f.prepminer(){
-  echo "Getting Miner"
-  echo "Move to a temporary work space"
-  cd /tmp
-  
   echo "Getting latest release of miner"
-  # Method if miner publishes git releases
-  #curl -s https://api.github.com/repos/fireice-uk/xmr-stak/releases/latest \
-  #| grep "browser_download_url.*tar\.gz" \
-  #| cut -d '"' -f 4 \
-  #| head -1 \
-  #| wget -qi -
-  # OR method if you have a direct url
-  wget https://github.com/cynixx3/third-party-miner-installer-for-ethos/raw/master/opt/miners/phoenixminer-4b.tar.gz
-  
+# Method for getting latest git release
+  curl -s https://api.github.com/repos/cynixx3/third-party-miner-installer-for-ethos/releases/latest \
+  | grep "browser_download_url.*tar\.gz" \
+  | cut -d '"' -f 4 \
+  | head -1 \
+  | wget -qi - -O PhoenixMiner.tar.gz
+# OR method if you have a direct url
+#  wget https://github.com/cynixx3/third-party-miner-installer-for-ethos/raw/master/opt/miners/phoenixminer-4b.tar.gz
+
   echo "Comparing download with checksum"
-  echo "354307c366d32b37793022aced287f6a76dc1037e98ab18d1af400bc532ba0d2 PhoenixMiner_4.0b_Linux.tar.gz" | sha256sum -c 
-  if [ "$?" -ne "0" ];then echo "checksum of downloaded files failed, please try again";exit 0; fi
+  echo "354307c366d32b37793022aced287f6a76dc1037e98ab18d1af400bc532ba0d2 PhoenixMiner.tar.gz" | sha256sum -c 
+  if [ "$?" -ne "0" ]; then echo "checksum of downloaded files failed, please try again";exit 1; fi
   
   echo "Unpacking miner"
-  tar xzf /tmp/PhoenixMiner_4.0b_Linux.tar.gz 
+  tar xzf $TMP_DIR/PhoenixMiner.tar.gz
   if [ "$?" != "0" ]; then
     echo "Unable to extract files package. please try again."
-    exit 0
+    exit 2
   fi
   
-  mkdir -p opt/miners
-  mv PhoenixMiner_4.0b_Linux opt/miners/phoenixminer
+  mkdir -p $TMP_DIR/opt/miners
+  rsync -a --delete $TMP_DIR/PhoenixMiner_4.0b_Linux/ $TMP_DIR/opt/miners/phoenixminer
   
   echo "Temporary miner files ready"
 }
@@ -52,24 +52,33 @@ f.checkdpkg(){
 
 f.prepethos(){
   echo "Download and unpack files needed by ethOS"
-  git clone https://github.com/cynixx3/ethOS-controller.git
+  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b phoenixminer
   
-  mkdir opt/ethos
-  mv third-party-miner-installer-for-ethos/opt/ethos/* opt/ethos
-  
+  mkdir -p $TMP_DIR/opt/ethos
+  rsync -a --delete $TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/ $TMP_DIR/opt/ethos
+  chmod ug+x $TMP_DIR/opt/ethos/*
+
 #  echo "Check for dependencies"
 #  if [ $(dpkg-query -W -f='${Status}' gcc-5 2>/dev/null | grep -c "ok installed") -eq 0 ] ; then
 #    echo "Installing dependencies"
-#    mkdir depends
+#    mkdir $TMP_DIR/depends
 #    wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/gcc-5-base_5.4.0-6ubuntu1~16.04.10_amd64.deb -P depends
 #    wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb -P depends
 #    f.checkdpkg
 #    sudo dpkg --configure -a
 #    f.checkdpkg
-#    sudo dpkg -i depends/*.deb
+#    sudo dpkg -i $TMP_DIR/depends/*.deb
 #  fi
   
   echo "ethOS files ready"
+}
+
+f.revert(){
+  git clone https://github.com/cynixx3/third-party-miner-installer-for-ethos.git -b ethos-1.3.3
+  mkdir -p $TMP_DIR/opt/ethos
+  rsync -a --delete $TMP_DIR/third-party-miner-installer-for-ethos/opt/ethos/ $TMP_DIR/opt/ethos
+  chmod ug+x $TMP_DIR/opt/ethos/lib/* $TMP_DIR/opt/ethos/bin/* $TMP_DIR/opt/ethos/sbin/*
+  chmod u+x $TMP_DIR/opt/ethos/etc/*
 }
 
 f.install(){
@@ -78,7 +87,7 @@ f.install(){
   /opt/ethos/bin/minestop
   
   echo "Installing miner"
-  sudo cp -R opt /
+  sudo rsync -av $TMP_DIR/opt/ /opt
   sudo chown -R ethos.ethos /opt/miners/
   
   echo "Restarting services and miner"
@@ -88,17 +97,30 @@ f.install(){
   /opt/ethos/bin/allow
 }
 
+f.cleanup(){
+  rm -rf $TMP_DIR
+}
+
 case "$1" in
   install)
     f.prepminer
     f.prepethos
     f.install
+    f.cleanup
   ;;
   update)
     f.prepminer
     f.install
+    f.cleanup
+  ;;
+  revert)
+    f.revert
+    rm -rf /opt/miners/phoenixminer
+    f.install
+    f.cleanup
   ;;
   *)
-    echo $"Usage: $0 {install|update}"
+    echo $"Usage: $0 {install|update|revert}"
     exit 1
 esac
+cd ~
